on: [push, workflow_dispatch]

name: CI

jobs:
  build-docker-container:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm ci

      - name: Build the docker image
        run: |
          export TAG=${GITHUB_SHA:0:8}
          echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin
          docker-compose -f docker-compose.yaml build
        if: github.ref == 'refs/heads/master' || contains(github.ref,'bdc_')
        env:
          DOCKER_USERNAME: ${{ github.repository }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: branch Push Docker image to github package registry
        run: |
          export TAG=${GITHUB_SHA:0:8}
          echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin
          docker-compose -f docker-compose.yaml push
        if: github.ref == 'refs/heads/master' || contains(github.ref,'bdc_')
        env:
          DOCKER_USERNAME: ${{ github.repository }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image with latest tag
        run: |
          echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin
          docker-compose -f docker-compose.yaml build
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ github.repository }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: branch Push Docker image to github package registry with latest tag
        run: |
          echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin
          docker-compose -f docker-compose.yaml push
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ github.repository }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
