name: Generate package-lock.json

on:
  push:
    branches:
      - main

jobs:
  generate-package-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Generate package-lock.json
        run: npm i --package-lock-only

      - name: Archive package-lock.json
        uses: actions/upload-artifact@v2
        with:
          name: package-lock
          path: ./package-lock.json

